# Week 4 - Data organising with Pandas

Author: Johanne Sejrskild  
Date: 22.09.2025

*Good afternoon*  
Today we are going to work with loops, condions and using ´pandas´to manipulate data. The green excercises will be highly linked to what you livecoded with Anna. If you find them challenging use yesterdays work as a help or ask. If you want to challenge yourself, try and do them all without using any help. 
In the yellow  excercises we will do some data manipulation challenges using pandas. And we will skip the red tasks today as we have a lot on the program

**Structure of the notebook:**  
<span style="color:green">
Green excercises 
</span>
<ul>
  <li> Data wrangling on the iris dataset</li>
</ul>

<span style="color:yellow">
Yellow excercises
</span>
<ul>
  <li>Music sales challenge</li>
  <li>Space mission challenge</li>
  <li>Supervillan challenge</li>
</ul>
 

Start with the first excercise, and then continue in order. Feel free to work together, and see how far you can get.   
The important thing is to learn, not to solve all the challenges!
________________________________________________________________________________________

In [56]:
# Before we start we need to import the necessary packages - ater you 

#%pip install pandas
#%pip install lxml
#%pip install scikit-learn

import pandas as pd
import requests # might need this package to get some data from web
from sklearn import datasets
from io import StringIO
from datetime import datetime

<span style="color:green">
<h2>
Green excercises </h2>
</span>

## Data organisation using a dataset about flowers

In [32]:
flower = datasets.load_iris()

# convert to DataFrame
df = pd.DataFrame(flower.data, columns=flower.feature_names)

df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


**Lets take a look at the data frame**

In [33]:
# Commands in pandas that can give you a quick overview of the data:

df.head()      # first 5 rows, use paranthesis you can decide rows
df.tail()      # last 5 rows
df.info()      # summary of columns and types
df.describe()  # quick statistics (for numbers)

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

**Selecting columns and rows**

Try to run the cell below and figure out which output is linked to the code

In [34]:
# If you want to select a specific column, select it using name:
print(df['sepal length (cm)'].head())

# If you would like to print one row, use the index of the row:
print(df.iloc[0])

# if you want to select a few rows of only a few columns:
print(df.iloc[0:3 , 0:2])  # first three rows, first two columns

# And if you want to select specific data, 
# you can specify a single row and column:
print(df.iloc[2,0])  # second row, first column

# Or use the column name:
print(df.loc[2, "sepal length (cm)"]  )

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64
sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64
   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
4.7
4.7

**Subsetting data**   
Subsetting is the process of retrieving just the parts of large files which are of interest for a specific purpose.   
This will come in handy for your projects when you have to work with potentially large data files

In [35]:
# Let's try to select some data using conditionals

# Select all rows where sepal length is >= to 5 cm:

lengt_above_five = df[df["sepal length (cm)"] >= 5]   
lengt_above_five.head()

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
7                 5.0               3.4                1.5               0.2
10                5.4               3.7                1.5               0.2

In [36]:
# Rows where sepal length is >= to 5 cm and the sepal width < 3,5 cm:

length_and_width = df[(df["sepal length (cm)"] >= 5
                      ) & (df["sepal width (cm)"] < 3.5)]
length_and_width.head()

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                 5.0               3.4                1.5               0.2
20                5.4               3.4                1.7               0.2
23                5.1               3.3                1.7               0.5
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4

In [57]:
# Excercise - Find longest petal length and median petal length

#use .max() function on petal length
longest_petal_length = df['petal length (cm)'].max()
# print message
print(f"The longest petal length is {longest_petal_length} cm")

#use .median() function on petal length
median_petal_length = df['petal length (cm)'].median()
# print message
print(f"The median petal length is {median_petal_length} cm") 

# subset flowers between the median and one cm shorter than max
subsest_median_and_max = df[(df["petal length (cm)"] 
                             >= median_petal_length) & (
    df["petal width (cm)"] < (longest_petal_length-1))]

# print first 5 rows:
subsest_median_and_max.head()

The longest petal length is 6.9 cm
The median petal length is 4.35 cm

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                7.0               3.2                4.7               1.4
51                6.4               3.2                4.5               1.5
52                6.9               3.1                4.9               1.5
54                6.5               2.8                4.6               1.5
55                5.7               2.8                4.5               1.3

**Sorting data**  
We can choose to sort our data in order of something of interest.

In [38]:
# sort the data by a specific column (ascending or descending):

# change direction by True/False:
df_sorted = df.sort_values(by="sepal length (cm)", ascending=False) 

df_sorted.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
131                7.9               3.8                6.4               2.0
122                7.7               2.8                6.7               2.0
118                7.7               2.6                6.9               2.3
117                7.7               3.8                6.7               2.2
135                7.7               3.0                6.1               2.3

In [39]:
# Excercise - sort the data by petal width in ascending order 
# and select the 10 flowers with the smallest petal width

df_sorted_petal = df.sort_values(by="petal width (cm)", 
                                 ascending=True)

df_sorted_petal_10_rows = df_sorted_petal.iloc[0:10]

df_sorted_petal_10_rows.head(10)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
9                 4.9               3.1                1.5               0.1
32                5.2               4.1                1.5               0.1
37                4.9               3.6                1.4               0.1
1                 4.9               3.0                1.4               0.2
4                 5.0               3.6                1.4               0.2
0                 5.1               3.5                1.4               0.2
11                4.8               3.4                1.6               0.2
10                5.4               3.7                1.5               0.2

**Flipping**  
Should you work with time seires data and would like to mirror (flip) your data, you can do this using pandas

In [40]:
print(df.head(5))

# Flipping the dataframe horisontally (reverse rows)
reversed_df = df.iloc[::-1]  

print(reversed_df.head(5))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
149                5.9               3.0                5.1               1.8
148                6.2               3.4                5.4               2.3
147                6.5               3.0                5.2               2.0
146                6.3               2.5                5.0               1.9
145                6.7               3.0                5.2               2.3

**Joining**
Sometimes we have multiple dataframes we woudl like to add together. Maybe you have been subsetting parts of an old dataframe to substract important information and would now like join them so you can begin your analysis.

In [41]:
# Joining a bit of the iris data with a new dataframe 
# We will make up some data here:

# selecting the first 10 rows of the iris data
first_10 = df.iloc[0:10, :] 

new_data = {"color": ["red", "blue", "green", "yellow", 
                      "purple", "red", "blue", "green", 
                      "yellow", "purple"],
            "height": [80, 80, 70, 100, 90, 80, 80, 70, 
                       100, 90]}

# new_df is a dictionary, convert it to a dataframe

new_df = pd.DataFrame(new_data)

#Now we join the two dataframes

# There are 4 different types of how: outer, inner, left, right. 
joined_left = first_10.join(new_df, how='left')

joined_left

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90

*Different types of how to join two data frames*  
This is important if your dataframes do not have the same amount of rows

left → all rows from the left DataFrame - and the ones matching from the right.

right → all rows from the right DataFrame - and the ones matching from the right.

inner → only rows with matching index values (rows) in both.

outer → all rows from both, fill missing with NaN.

In [42]:
# Excercise - Which types of join will work? 
# Try them out and see what happens

# joined right: 

joined_right = first_10.join(new_df, how='right') 

joined_right

# joined outer: 

joined_outer = first_10.join(new_df, how='outer') 

joined_outer

# joined inner: 

joined_inner = first_10.join(new_df, how='inner') 

joined_inner

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90

**All of them has the excact same out. Perhaps, because they each have the same amount of rows.**

In [43]:
# Excercise 2 - Add a row to one of the dataframes
# Then see what happens when you join them again

new_data_2 = {"color": ["red", "blue", "green", "yellow", 
                        "purple", "red", "blue", "green", 
                        "yellow", "purple", "green"],
            "height": [80, 80, 70, 100, 90, 80, 80, 70, 
                       100, 90, 91]}

new_df_2 = pd.DataFrame(new_data_2)

# joined outer: 

joined_outer_2 = first_10.join(new_df_2, how='outer') 

joined_outer_2

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90
10,NaN,NaN,NaN,NaN,green,91

**When now joining them again, a row with NaN appears.**

**Concatenating**  
You can also join two dataframes by simply gluing them together.

In [44]:
# We just made a subset of the original dataframe called 'first_10' 
# now we find the last 10 and glue them together

# selecting the last 10 rows using one of the methods we learned
last_10 = df.iloc[-10:, :]  

# Now we concatenate the two dataframes together 
# axis=0 means we concatenate rows, axis=1 would concatenate columns
concatenated = pd.concat( [first_10, last_10], axis=0) 
concatenated

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

Now you have played around with some of the basics manipulation in pandas! Now lets jump into some challenges

<span style="color:yellow">
<h2>
Yellow excercises 
</span>

**OBS:**  To ensure you can go back in 3 months time and read you code and understand the logics behind it it needs to be well commented.   
So, while you solve the yellow excercises ensure that you add some meaningful comments about the logics and coding choices.  

:))


*The Yellow excercises is borrowed from the 2024 couse written by Ethan Weed*

**Music sales challenge**

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
3. Outputs the artist and single name for the year you were 15 years old.

In [61]:
# Starter code
url_music = "https://en.wikipedia.org/wiki/List_of_best-selling_singles"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_music, headers=headers)

# Pass the HTML text to pandas
musicdata = pd.read_html(StringIO(response.text))

#Extracting physical and digital singles from the musicdata
physical_singles = musicdata[0]
digital_singles = musicdata[3]

physical_singles["Type"] = "Physical"
digital_singles["Type"] = "Digital"

# Combining the two tables
combined_singles = pd.concat(
    [physical_singles, digital_singles],
    ignore_index=True
)

combined_singles.head()

,Year,Single,Artist,Claimed sales (in million),Ref.,Type,Units (in million)
0,1935.0,"""Silent Night""",Bing Crosby,30.0,[11],Physical,NaN
1,1942.0,"""White Christmas""",Bing Crosby,50.0,[5],Physical,NaN
2,1946.0,"""Petit Papa Noël""",Tino Rossi,30.0,[12],Physical,NaN
3,1954.0,"""Rock Around the Clock""",Bill Haley & His Comets,25.0,[13][14],Physical,NaN
4,1960.0,"""It's Now or Never""",Elvis Presley,20.0,[15][16],Physical,NaN

In [63]:
# Print the artist and single from the year you were born

#Hint: combined_singles[combined_singles['Year']] 
# finds the column with all the years songs were released:
singles_my_2004 = combined_singles[combined_singles
    ['Year'] == 2004.0]
singles_my_2004

# closest year to me: 
singles_my_2010 = combined_singles[combined_singles
    ['Year'] == 2010.0]

# print it out:
print(singles_my_2010[['Artist', 'Single', 'Year']])

  Artist                 Single    Year
8  Adele  "Rolling in the Deep"  2010.0

In [64]:
# Print the artist and single from the year you were 15 years old. 

# 15 year old:
singles_my_2019 = combined_singles[combined_singles
    ['Year'] == 2019.0]

# print it out:
print(singles_my_2019[['Artist', 'Single', 'Year']])

           Artist     Single    Year
17  Billie Eilish  "Bad Guy"  2019.0

## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [65]:
# Starter code.
url_space =  "https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_space, headers=headers)

# Pass the HTML text to pandas
spacedata = pd.read_html(StringIO(response.text))

# combine all tables into data frame
combined_space = pd.concat(spacedata, 
                           ignore_index = True)

# Dropping column we dont need
combined_space = combined_space.iloc[:, 0:3]
combined_space.head()

,Mission name,Launch date,Description
0,Sputnik 1,4 October 1957,First Earth orbiter
1,Sputnik 2,3 November 1957,"Earth orbiter, first animal in orbit, a dog na..."
2,Explorer 1,1 February 1958,Earth orbiter; discovered Van Allen radiation ...
3,Vanguard 1,17 March 1958,Earth orbiter; oldest spacecraft still in Eart...
4,Luna 1,2 January 1959,First lunar flyby (failed lunar impact); first...

In [68]:
## The year with the most launches 

# Hint:  we want the column 'Launch date', 
# only the rows with a date, and then converteed to a string

# select columns with launch dates: 
launch_dates = combined_space[["Launch date"]]

# remove NaN:
launch_dates = launch_dates.dropna()

# convert the dates: 
launch_dates["Launch date"] = pd.to_datetime(launch_dates
    ['Launch date'], format='%d %B %Y')

# get column with the year: 
launch_dates['Year'] = launch_dates['Launch date'].dt.year

# to get column with the month: 
launch_dates['Month'] = launch_dates['Launch date'].dt.month
launch_dates['Month'] = pd.to_datetime(launch_dates['Month'], 
                                       format='%m').dt.strftime('%b')

# to get the year with the most launches: 
# group launches by year to count them
launches_year = launch_dates.groupby('Year').size()
# find the max amount of launches by year
max_year = launches_year.max() 
# find the year that has the max amount of launches
years_with_max = launches_year[launches_year == max_year].index 

# use a for-loop to go through years (if more years with max launches): 
for year in years_with_max:
    print(f"The year {year} had the most launches at"
    f" {max_year} launches.") # print the message

The year 1965 had the most launches at 12 launches.
The year 1967 had the most launches at 12 launches.

In [69]:
# The month with the most launches:

# count the max launches by month
most_launches_month = launch_dates['Month'].value_counts().max()
# finds the month
launches_month = launch_dates['Month'].value_counts().idxmax() 

# print the message
print(f"{launches_month} had the most launches at"
f" {most_launches_month} launches.")

Nov had the most launches at 31 launches.

In [70]:
# Ranking of months with the most to the fewest launches

most_launches_month = launch_dates['Month'
    ].value_counts() # counts launches by month

most_launches_month

Month
Nov    31
Aug    28
Sep    25
Oct    24
Jul    22
Jan    21
May    19
Dec    19
Feb    18
Mar    15
Apr    14
Jun    14
Name: count, dtype: int64

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [75]:
#supervillandata = 
# pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")

url_villan = "https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_villan, headers=headers)

# Pass the HTML text to pandas
supervillandata = pd.read_html(StringIO(response.text))

# combine all tables into data frame
df_supervillain = pd.concat(supervillandata, 
                            ignore_index = True)
df_supervillain.head()

,0,1,Character / Team,Year Debuted,Company,Creator/s,First Appearance
0,NaN,This article has multiple issues. Please help ...,NaN,NaN,NaN,NaN,NaN
1,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
2,NaN,This article needs more citations. Please help...,NaN,NaN,NaN,NaN,NaN
3,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
4,NaN,This article needs more citations. Please help...,NaN,NaN,NaN,NaN,NaN

In [76]:
# 1. Write a script that combines the tables, 
# showing supervillain debuts from the 30's through the 2010's

# remove first 5 rows and first 2 columns: 
df_supervillain = df_supervillain.iloc[5: , 2:]

# remove all NaNs: 
df_supervillain = df_supervillain.dropna()

# get year only by only taking first 4 characters of string: 
df_supervillain['Year Debuted'] = df_supervillain[
    'Year Debuted'].str[:4]

# remove what isn't a numeric year:
df_supervillain = df_supervillain[df_supervillain[
    'Year Debuted'].str.isnumeric()]

# have a look at the data now: 
df_supervillain.head()

,Character / Team,Year Debuted,Company,Creator/s,First Appearance
5,Ultra-Humanite,1939,DC,"Jerry Siegel, Joe Shuster",Action Comics (vol. 1) #13
6,Dr. Death,1939,DC,"Bob Kane, Bill Finger",Detective Comics (vol. 1) #29
7,The Monk,1939,DC,"Bob Kane, Bill Finger",Detective Comics (vol. 1) #31
8,The Claw,1939,Lev Gleason Publications,Jack Cole,Silver Streak Comics #1
10,Hath-Set,1940,DC,"Gardner Fox, Dennis Neville",Flash Comics #1

In [77]:
# 2. Write a script that ranks each decade, 
# in terms of how many supervillains debuted in that decade

# make a column with decade in the df: 
df_supervillain['Decade'] = (df_supervillain[
    'Year Debuted'].astype(int) // 10) * 10

# group by decade to count amount of supervillains:
df_decade = df_supervillain.groupby('Decade').size()

# sort the values:
df_decade_sorted = df_decade.sort_values(ascending=False)

# show the output: 
df_decade_sorted

Decade
1960    212
1970     87
1980     73
1990     72
2000     50
1940     44
1950     20
2010     16
2020      9
1930      4
dtype: int64

In [55]:
# 3. Write a script that ranks the different comics companies,
# in terms of how many supervillains they have:

comic_companies = df_supervillain['Company'].value_counts()

comic_companies

Company
DC                          280
Marvel                      253
Image Comics                 17
Image                        13
Fawcett Comics/DC             5
Dark Horse                    5
Marvel/Timely                 4
Disney/Hyperion               4
Eternity                      3
Lev Gleason Publications      1
Comico                        1
Mirage                        1
Name: count, dtype: int64