# Week 4 - Data organising with Pandas

Author: Johanne Sejrskild  
Date: 22.09.2025

*Good afternoon*  
Today we are going to work with loops, condions and using ´pandas´to manipulate data. The green excercises will be highly linked to what you livecoded with Anna. If you find them challenging use yesterdays work as a help or ask. If you want to challenge yourself, try and do them all without using any help. 
In the yellow  excercises we will do some data manipulation challenges using pandas. And we will skip the red tasks today as we have a lot on the program

**Structure of the notebook:**  
<span style="color:green">
Green excercises 
</span>
<ul>
  <li> Data wrangling on the iris dataset</li>
</ul>

<span style="color:yellow">
Yellow excercises
</span>
<ul>
  <li>Music sales challenge</li>
  <li>Space mission challenge</li>
  <li>Supervillan challenge</li>
</ul>
 

Start with the first excercise, and then continue in order. Feel free to work together, and see how far you can get.   
The important thing is to learn, not to solve all the challenges!
________________________________________________________________________________________

In [5]:
# Before we start we need to import the necessary packages
#%pip install pandas
#%pip install lxml
#%pip install scikit-learn

import pandas as pd
import requests # We might need this package to get some data from the web
from sklearn import datasets
from io import StringIO

<span style="color:green">
<h2>
Green excercises </h2>
</span>

## Data organisation using a dataset about flowers

In [ ]:
flower = datasets.load_iris()

# convert to DataFrame
df = pd.DataFrame(flower.data, columns=flower.feature_names)

df.head()


**Lets take a look at the data frame**

In [ ]:
# There are some commands in the library pandas that can give you a quick overview of the data :)

df.head()      # first 5 rows, if you put a number into the paranthesis you can decide how many rows
df.tail()      # last 5 rows
df.info()      # summary of columns and types
df.describe()  # quick statistics (for numbers)

**Selecting columns and rows**

Try to run the cell below and figure out which output is linked to the code

In [ ]:
# If you want to select a specific column you can select it using the name:
print(df['sepal length (cm)'].head())

# If you would like to print one row, you can use the index of the row:
print(df.iloc[0])

# if you want to select a few rows of only a few columns you can also use indexing:
print(df.iloc[0:3 , 0:2])  # first three rows, first two columns

# And if you want to select specific data, you can specify a single row and column:
print(df.iloc[2,0])  # second row, first column

# Or use the column name:
print(df.loc[2, "sepal length (cm)"]  )

**Subsetting data**   
Subsetting is the process of retrieving just the parts of large files which are of interest for a specific purpose.   
This will come in handy for your projects when you have to work with potentially large data files

In [ ]:
# Let's try to select some data using conditionals

# Here we select all rows where the sepal length is larger than or equal to 5 cm
lengt_above_five = df[df["sepal length (cm)"] >= 5]   
lengt_above_five.head()

In [ ]:
# Here we select all rows where the sepal length is larger than or equal to 5 cm and the sepal width is less than 2,5 cm
length_and_width = df[(df["sepal length (cm)"] >= 5) & (df["sepal width (cm)"] < 3.5)]
length_and_width.head()

In [ ]:
# Excercise - Find the longest petal length and the median petal length
# and subset the flowers that are between the median and one centimeter shorter than max length

max = df["petal length (cm)"].max()
median = df["petal length (cm)"].median()

long_flowers = df[(df["petal length (cm)"] < max-1) & (df["petal length (cm)"] > median)]
long_flowers.head()
long_flowers.max() # checking that petal length is below max - 1 cm

**Sorting data**  
We can choose to sort our data in order of something of interest.

In [ ]:
# we could sort the data by a specific column in both ascending and descending order
df_sorted = df.sort_values(by="sepal length (cm)", ascending=False) # change direction by True/False so if you want ascending order set it to True
df_sorted.head()

In [ ]:
# Excercise - sort the data by petal width in ascending order and select the 10 flowers with the smallest petal width
df_sorted_petal = df.sort_values(by="petal width (cm)", ascending=True)
df_sorted_petal.head(10)

**Flipping**  
Should you work with time seires data and would like to mirror (flip) your data, you can do this using pandas

In [ ]:
print(df.head(5))

reversed_df = df.iloc[::-1]   # Flipping the dataframe horisontally (reverse rows)

print(reversed_df.head(5))

**Joining**
Sometimes we have multiple dataframes we woudl like to add together. Maybe you have been subsetting parts of an old dataframe to substract important information and would now like join them so you can begin your analysis.

In [33]:
# Joining a bit of the iris data with a new dataframe (we will make up some data here)
first_10 = df.iloc[0:10, :]  # selecting the first 10 rows of the iris data
new_data = {"color": ["red", "blue", "green", "yellow", "purple", "red", "blue", "green", "yellow", "purple"],
            "height": [80, 80, 70, 100, 90, 80, 80, 70, 100, 90]}
# Right now new_df is a dictionary, we need to convert it to a dataframe
new_df = pd.DataFrame(new_data)

#Now we join the two dataframes
joined = first_10.join(new_df, how='outer') # There are 4 different types of how: outer, inner, left, right. 

joined

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90

*Different types of how to join two data frames*  
This is important if your dataframes do not have the same amount of rows

left → all rows from the left DataFrame (default).

right → all rows from the right DataFrame.

inner → only rows with matching index values in both.

outer → all rows from both, fill missing with NaN.

In [ ]:
# Excercise - Which types of join (the 'how=') will work in the example above? Try them out and see what happens

# They all give the same output - that must be because they are identical in the rows

In [38]:
# Excercise 2 - Add a row to one of the dataframes and see what happens when you join them again

first_10 = df.iloc[0:10, :]  # selecting the first 10 rows of the iris data
new_data_extra_row = {"color": ["red", "red", "blue", "green", "yellow", "purple", "red", "blue", "green", "yellow", "purple"],
            "height": [80, 80, 70, 90, 100, 90, 80, 80, 70, 100, 90]}
# Right now new_df is a dictionary, we need to convert it to a dataframe
new_data_extra_row = pd.DataFrame(new_data_extra_row)

#Now we join the two dataframes
joined = first_10.join(new_data_extra_row, how='right') # There are 4 different types of how: outer, inner, left, right. 

joined

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,red,80
2,4.7,3.2,1.3,0.2,blue,70
3,4.6,3.1,1.5,0.2,green,90
4,5.0,3.6,1.4,0.2,yellow,100
5,5.4,3.9,1.7,0.4,purple,90
6,4.6,3.4,1.4,0.3,red,80
7,5.0,3.4,1.5,0.2,blue,80
8,4.4,2.9,1.4,0.2,green,70
9,4.9,3.1,1.5,0.1,yellow,100
10,NaN,NaN,NaN,NaN,purple,90

**Concatenating**  
You can also join two dataframes bu simply gluing them together.

In [ ]:

# We just made a subset of the original dataframe called 'first_10' now we find the last 10 and glue them together
last_10 = df.iloc[-10:, :]   # selecting the last 10 rows using one of the methods we learned above


# Now we concatenate the two dataframes together 
concatenated = pd.concat( [first_10, last_10], axis=0)  # axis=0 means we concatenate rows, axis=1 would concatenate columns
concatenated

Now you have played around with some of the basics manipulation in pandas! Now lets jump into some challenges

<span style="color:yellow">
<h2>
Yellow excercises 
</span>

**OBS:**  To ensure you can go back in 3 months time and read you code and understand the logics behind it it needs to be well commented.   
So, while you solve the yellow excercises ensure that you add some meaningful comments about the logics and coding choices.  

:))


*The Yellow excercises is borrowed from last years couse and written by Ethan Weed*

**Music sales challenge**

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
3. Outputs the artist and single name for the year you were 15 years old.

In [ ]:
# Starter code
#musicdata = pd.read_html("https://en.wikipedia.org/wiki/List_of_best-selling_singles")
url_music = "https://en.wikipedia.org/wiki/List_of_best-selling_singles"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_music, headers=headers)

# Pass the HTML text to pandas
musicdata = pd.read_html(StringIO(response.text))


#Extracting physical and digital singles from the musicdata
physical_singles = musicdata[0]
digital_singles = musicdata[3]

physical_singles['Type'] = 'Physical'
digital_singles['Type'] = 'Digital'

# Combining the two tables
combined_singles = pd.concat([physical_singles, digital_singles])
combined_singles.head()

In [ ]:
# Simple Version
# Print the name of the artist and the single from the year you were born - or the year closest to.

birth_year_singles = combined_singles[combined_singles['Year'] == 2000.0] # locate release year, manually change the year until you find a single and artist. 
print(birth_year_singles[['Artist', 'Single', 'Year']]) # see single and artist

In [ ]:
# Automated version: Adding it to a loop that automatically searches. 
# Print the name of the artist and the single from the year you were born - or the year closest to.

birth_year = 2000

birth_year_singles = combined_singles[combined_singles['Year'] == birth_year]

if not birth_year_singles.empty:
    print(f"Singles from the year {birth_year}:")
    print(birth_year_singles[['Artist', 'Single']])
else:
    print(f"No singles found from the year {birth_year}. Searching closest years...")

    found_singles = False
    offset = 1

    while not found_singles:
        year_before = birth_year - offset
        year_after = birth_year + offset

        singles_before = combined_singles[combined_singles['Year'] == year_before]
        singles_after = combined_singles[combined_singles['Year'] == year_after]

        if singles_before.empty:
            print(f"Checked {year_before}: no singles found.")
        if singles_after.empty:
            print(f"Checked {year_after}: no singles found.")

        if not singles_before.empty:
            print(f"Singles from the year {year_before}:")
            print(singles_before[['Artist', 'Single']])
            found_singles = True
        elif not singles_after.empty:
            print(f"Singles from the year {year_after}:")
            print(singles_after[['Artist', 'Single']])
            found_singles = True

        offset += 1

In [ ]:
# Print the arrtist and single from the year you were 15 years old. 

birth_year = 2000+15

birth_year_singles = combined_singles[combined_singles['Year'] == birth_year]

if not birth_year_singles.empty:
    print(f"Singles from the year {birth_year}:")
    print(birth_year_singles[['Artist', 'Single']])
else:
    print(f"No singles found from the year {birth_year}. Searching closest years...")

    found_singles = False
    offset = 1

    while not found_singles:
        year_before = birth_year - offset
        year_after = birth_year + offset

        singles_before = combined_singles[combined_singles['Year'] == year_before]
        singles_after = combined_singles[combined_singles['Year'] == year_after]

        if singles_before.empty:
            print(f"Checked {year_before}: no singles found.")
        if singles_after.empty:
            print(f"Checked {year_after}: no singles found.")

        if not singles_before.empty:
            print(f"Singles from the year {year_before}:")
            print(singles_before[['Artist', 'Single']])
            found_singles = True
        elif not singles_after.empty:
            print(f"Singles from the year {year_after}:")
            print(singles_after[['Artist', 'Single']])
            found_singles = True

        offset += 1

## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [6]:
# Starter code.
url_space =  "https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_space, headers=headers)

# Pass the HTML text to pandas
spacedata = pd.read_html(StringIO(response.text))

# combine all tables into data frame
combined_space = pd.concat(spacedata, ignore_index = True)

# Dropping column we dont need
combined_space = combined_space.iloc[:, 0:3]

combined_space.head()

,Mission name,Launch date,Description
0,Sputnik 1,4 October 1957,First Earth orbiter
1,Sputnik 2,3 November 1957,"Earth orbiter, first animal in orbit, a dog na..."
2,Explorer 1,1 February 1958,Earth orbiter; discovered Van Allen radiation ...
3,Vanguard 1,17 March 1958,Earth orbiter; oldest spacecraft still in Eart...
4,Luna 1,2 January 1959,First lunar flyby (failed lunar impact); first...

In [7]:
## The year with the most launches - Simple version ##

# print the column names
print(combined_space.columns)
launch_date = combined_space['Launch date'] #The column name we want is 'Launch date'
launch_date_clean = launch_date.dropna() # drop rows with NaN values
launch_date_clean = launch_date_clean.astype(str) # convert to string


# Extract the year from the launch date - last 4 digits
launch_counts = launch_date_clean.str[0:4].value_counts().reset_index()
launch_counts
print(launch_counts.head(2))

Index(['Mission name', 'Launch date', 'Description'], dtype='object')
  Launch date  count
0        3 Ma      4
1        12 A      4

In [8]:
# The year with the most launches - Other version

# Convert the 'Launch Date' column to datetime - which we will also need for the next tasks 
combined_space['Launch date'] = pd.to_datetime(combined_space['Launch date'], format='%d %B %Y')
combined_space['Year'] = combined_space['Launch date'].dt.year

launches_year = combined_space.groupby('Year').size() # The launches per year

# Find all years with the max count, as there might be more than one
max_count = launches_year.max()
years_with_max = launches_year[launches_year == max_count].index

# Print all years with their count
for year in years_with_max:
    print(f"The year with the most launches is {year}, with {max_count} launches.")

The year with the most launches is 1965.0, with 12 launches.
The year with the most launches is 1967.0, with 12 launches.

In [9]:
# The month with the most launches - Simple version

# Isolate the month from the datetime column and create new column in df
combined_space['Month'] = combined_space['Launch date'].dt.month

missionspermonth = combined_space.groupby('Month').size()
print(missionspermonth)
# Find the months with the most missions
month_with_most_missions = missionspermonth.idxmax()
month_most_missions_count = missionspermonth.max()

# Ensure month_with_most_missions is an integer
month_with_most_missions = int(month_with_most_missions)

# Print the result in a sentence
print(f"The month with the most missions is the {month_with_most_missions}th month, with {month_most_missions_count} missions.")

Month
1.0     21
2.0     18
3.0     15
4.0     14
5.0     19
6.0     14
7.0     22
8.0     28
9.0     25
10.0    24
11.0    31
12.0    19
dtype: int64
The month with the most missions is the 11th month, with 31 missions.

In [10]:
# Ranking of months with the most to the fewest launches
missionspermonth_sorted = missionspermonth.sort_values(ascending=False)
print(missionspermonth_sorted)

Month
11.0    31
8.0     28
9.0     25
10.0    24
7.0     22
1.0     21
12.0    19
5.0     19
2.0     18
3.0     15
4.0     14
6.0     14
dtype: int64

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [16]:
#supervillandata = pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")

url_villan = "https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_villan, headers=headers)

# Pass the HTML text to pandas
supervillandata = pd.read_html(StringIO(response.text))


# combine all tables into data frame
df_supervillan = pd.concat(supervillandata, ignore_index = True)
df_supervillan.head()

,0,1,Character / Team,Year Debuted,Company,Creator/s,First Appearance
0,NaN,This article has multiple issues. Please help ...,NaN,NaN,NaN,NaN,NaN
1,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
2,NaN,This article needs more citations. Please help...,NaN,NaN,NaN,NaN,NaN
3,NaN,This article includes a list of general refere...,NaN,NaN,NaN,NaN,NaN
4,NaN,This article needs more citations. Please help...,NaN,NaN,NaN,NaN,NaN

In [17]:
# 1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's

# Remove the first five rows as they are super wierd
df_supervillan = df_supervillan.iloc[5:]
# keep only the first 4 letters in the year column
df_supervillan['Year Debuted'] = df_supervillan['Year Debuted'].str[:4]
#remove the instances where the year is not a number
df_supervillan = df_supervillan[df_supervillan['Year Debuted'].str.isnumeric()]
# remove the first two columns as they are NaN
df_supervillan = df_supervillan.iloc[:, 2:]


df_supervillan.head()

,Character / Team,Year Debuted,Company,Creator/s,First Appearance
5,Ultra-Humanite,1939,DC,"Jerry Siegel, Joe Shuster",Action Comics (vol. 1) #13
6,Dr. Death,1939,DC,"Bob Kane, Bill Finger",Detective Comics (vol. 1) #29
7,The Monk,1939,DC,"Bob Kane, Bill Finger",Detective Comics (vol. 1) #31
8,The Claw,1939,Lev Gleason Publications,Jack Cole,Silver Streak Comics #1
10,Hath-Set,1940,DC,"Gardner Fox, Dennis Neville",Flash Comics #1

In [ ]:
# 2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade

# make a new column with the decade
df_supervillan['Decade'] = (df_supervillan['Year Debuted'].astype(int) // 10) * 10 # Finding the decade by integer division and multiplying by 10

# Group the dataframe by Decade
grouped = df_supervillan.groupby('Decade')

# Now we count how many supervillains per decade
decade_counts = grouped.size()

# Lastly, sorting the counts from highest to lowest
decade_counts_sorted = decade_counts.sort_values(ascending=False) # We want the descending order
print(decade_counts_sorted)

In [ ]:
# 3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results 

company_counts = df_supervillan['Company'].value_counts()

print(company_counts)